### ISSUE TITLE
Can't compile on M1

### ISSUE THREAD

**Issue by ryangjchandler** [dannyvankooten/pepper-lang#1]
Struggling to run `make` on an M1 MacBook Pro. As far as I know, clang doesn't support the -march=native on M1 yet.

**Comment by dannyvankooten** [comment]
Hey @ryangjchandler,

Thanks for the heads up - I remove the flag entirely for now as the performance gains weren't really noticeable for me anyway and it's still trivial to add them where possible. Pretty cool that you're checking this out btw! I have no clue where I'm going with this, but it's a lot of fun playing around with it and checking other languages to see how they're dealing with stuff.

**Comment by ryangjchandler** [comment]
> Hey @ryangjchandler,
> 
> Thanks for the heads up - I removed the flag entirely for now as the performance gains weren't really noticeable for me anyway and it's still trivial to add them where possible. Pretty cool that you're checking this out btw! I have no clue where I'm going with this, but it's a lot of fun playing around with it and checking other languages to see how they're dealing with stuff.

Nice - I'll give it another go. Let me know if you need any assistance :)
